### ISSUE TITLE
Blacklisted Storage Datapack

### ISSUE THREAD

**Issue by SattesKrokodil** [Tfarcenim/DankStorageFabric#11]
Doesn't seem to work, the item gets the text "This item has been blacklisted from storage!" but it can be stored/picked up by the dank as usual.

![image](https://user-images.githubusercontent.com/20082712/107125021-7cf21880-68a7-11eb-88bd-44a2de37b17c.png)

**Comment by Tfarcenim** [comment]
fixed in 1.10
