### ISSUE TITLE
Ctrl not locking slot

### ISSUE THREAD

**Issue by xSnufflesx** [Tfarcenim/DankStorageFabric#12]
Not entirely sure if this is something wrong with the mod or just something due to my modlist somehow making it not work but when i hover over a slot in the dank and hit ctrl (left and right ctrl dont work) nothing happens.
Only keybind i could find that also uses Ctrl is sprint but even removing that didnt let the locking work.
Modlist in case its useful: https://i.imgur.com/Jf0dppe.png

Also just want to say i absolutely LOVE this mod. This is 100% hands down my new backpack mod for any future modded playthrus
*Bows before mod author*

**Comment by Tfarcenim** [comment]
probably a mod eating the ctrl key

**Comment by Tfarcenim** [comment]
it locks them now
