### ISSUE TITLE
Crashing Upon Opening a Dank

### ISSUE THREAD

**Issue by mahjerion** [Tfarcenim/DankStorageFabric#13]
https://pastebin.com/eTj3barW

Happens when one of the players on the server is opening their Dank. Hopefully you can shine some light on it!

**This is on:**
Craft to Exile [Harmony]
1.16.4
Fabric API 0.31.0
Dank dankstorage-1.9a-1.16.3

**Comment by Tfarcenim** [comment]
not able to figure this one out, but let me know if it's reproducible in 1.10
