### ISSUE TITLE
danks empty after updating from 0.9a to 0.10a !?!

### ISSUE THREAD

**Issue by MSandro** [Tfarcenim/DankStorageFabric#17]
after updating from Dank Storage Fabric 0.9a to 0.10a my danks are empty. I had to restore a world backup and downgrade to the older version.

**Comment by Tfarcenim** [comment]
held or docked?

**Comment by 0gp** [comment]
Placed

**Comment by MSandro** [comment]
Placed

**Comment by Tfarcenim** [comment]
Fun, does picking it up before updating fix it?

**Comment by aarch-angel** [comment]
I experienced the same issue, unfortunately in my case I don't have a world backup to test it out, sorry :(

**Comment by MarcusElg** [comment]
For me dank storages in docks loose all items when leaving the area

**Comment by Tfarcenim** [comment]
fixed in 2,0
