### ISSUE TITLE
Many crashes!

### ISSUE THREAD

**Issue by Dm5354** [Tfarcenim/DankStorageFabric#19]
The mod works fine ish..... if I use bag mode

No need for mod list or fabric version, everything in the reports.

Crash no.1
If I switch to the construction mode and try to place blocks it immediately crashes.

NVM the first crash, it is caused by tweakeroo, maybe a mod compability.
Tho I tested it with fast block placement - crash ; tested without it - crash
My only guess is that tweakeroo uses a custom method for placing blocks!

Report:
https://pastebin.pl/view/250e7813

Crash no.2
If I try to craft the Dank 7 it crashes when the recipe in the crafting grid is complete.

Report:
https://pastebin.pl/view/4bfcfe96

If anything else is needed msg me!

Ty

**Comment by Fourmisain** [comment]
Some additional info:
The construction mode crash happens without any other mods so it's not a mod compatibility thing.
No matter what I tried (filling every slot, placing it in a dock, reloading MC), it always crashes when placing.
Shift+scroll seems to always select the last slot and switching back to bag mode will still show the selected item.

**Comment by Dm5354** [comment]
I msg/d masa, the author of tweakeroo, and he figured out its a problem with how it handles the innventory:

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4169)
        at net.minecraft.class_2371.set(class_2371.java:53)
        at net.minecraft.class_1277.method_5447(class_1277.java:132)
        at tfar.dankstorage.item.DankItem.method_7884(DankItem.java:314)

method_7884 = useOnBlock
method_5447 = setStack
class_1277 = SimpleInventory
class_2371 = DefaultedList
which means that the DankItem has an inventory with the size of 0 slots and it tries to set an item in the first slot (which does not exist)

**Comment by Tfarcenim** [comment]
Fixed in 2.1
