### ISSUE TITLE
Dank losing items

### ISSUE THREAD

**Issue by b4mmb4mm2** [Tfarcenim/DankStorageFabric#20]
It might not be a problem with dank itself. Ever since updating to aof3 1.8.4, if I leave a dank in a dock and go to a different dimension, when I come back the storage is completely empty.

Like I said, it might not be dank itself, I also lose flight ability when going to different dimensions and have to relog to get it back.

**Comment by Tfarcenim** [comment]
DUplicate of https://github.com/Tfarcenim/DankStorageFabric/issues/18, fixed in 2.0
