### ISSUE TITLE
Using Water/Lava Buckets will set stack size back to 1

### ISSUE THREAD

**Issue by Fourmisain** [Tfarcenim/DankStorageFabric#21]
If you have multiple Water/Lava Buckets stacked in your dank and you try and place water/lava via construction mode, it will place the fluid, but it will also replace the whole bucket stack with a single empty bucket.

I ran into this with version 1.9a (and lost 81 buckets to it).
It's likely an issue in 2.0a as well, though I can't confirm that due to [construction mode crashing](https://github.com/Tfarcenim/DankStorageFabric/issues/19).

**Comment by Tfarcenim** [comment]
Confirmed, but I have not found a nice way of dealing with this as mojang assumes bucket sizes will always be 1.

**Comment by Tfarcenim** [comment]
This is a vanilla bug, but I don't know if it is within the scope of this mod to patch it, probably not.

**Comment by Tfarcenim** [comment]
In conclusion, I will not be fixing this bug as patching it would break other mods that do bucket stacking.
