### ISSUE TITLE
Dank IDs are can be changed to 0 and incremented using Dock

### ISSUE THREAD

**Issue by dandin87** [Tfarcenim/DankStorageFabric#22]
All Of Fabric 4 0.0.5 Public Server. I will also try to recreate with only Dank later tonight.
It would seem that placing a Dank in a Dock will set its ID to 0, then if you break the Dock and shift right click it, the returned Dank's ID will have Incremented. This can be abused to steal other peoples Dank inventories,
From the AoF Discord All-of-Fabric-4 channel.
punkystone: yeah thats probaly what happend, i placed a dank (in a dock) and it got assigned the id 0 and a different player did the same and also got the id 0, therefore overwriting my dank
punkystone: i am also able to increment the id of the dank by placing it in a dock, breaking the dock and shift right click the collected dank, not sure if this is intended
punkystone: yeah with incrementing the id you could probably view the dank of other people

**Comment by Tfarcenim** [comment]
Fixed in 2.1, although note that being able to change the id in an intended manner will be added in a future update with the ability to lock the id against unscrupulous players.

**Comment by dandin87** [comment]
FYI, Breaking the dock with the dank inside, drops both as items now, however the dank ID is still shifting to the next available ID. And so its inventory is empty.

**Comment by itsdinkd** [comment]
@Tfarcenim this is still true
