### ISSUE TITLE
Just upgraded my server to All Of Fabric 4 0.0.7, every time I open my Dank 7 the server crashes

### ISSUE THREAD

**Issue by b4mmb4mm2** [Tfarcenim/DankStorageFabric#24]
Tried it in a solo world, it also crashes. All my good stuff is in my Danks, hope this gets figured out quickly.

[crash-2021-07-20_09.50.39-server.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6849350/crash-2021-07-20_09.50.39-server.txt)

[solo crash-2021-07-20_10.00.16-server.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6849361/solo.crash-2021-07-20_10.00.16-server.txt)

**Comment by b4mmb4mm2** [comment]
Deleted 2.0a from the server, uploaded 2.0. I was able to get m y stuff out. Several spaces showed nothing inside, but when clicked it showed up. Putting my Danks in storage until the issue is resolved.

**Comment by b4mmb4mm2** [comment]
AOF 4 0.0.8 is out. Danks still crash the server

**Comment by Tfarcenim** [comment]
fixed in 2.1
