### ISSUE TITLE
Dank Linking / losing items with frames.

### ISSUE THREAD

**Issue by HillDragon** [Tfarcenim/DankStorageFabric#26]
Hello, we're running a 1.17 fabric server.

if someone places an empty dank in a frame it will often link to another dank. it could be anyone's on the server (we haven't confirmed if it's only to held dank or if it could be framed dank as well.)

this mean people are gaining access to other's inventory OR if it linked to an empty dank it means they're adding to someone's inventory and if they pick it up they lose their stuff to whom ever it went to.

i can attempt to troubleshoot / replicate if you would like.

**Comment by HillDragon** [comment]
mod list can be found here if you think it's relation/dependent related. 
https://www.curseforge.com/minecraft/modpacks/nearly-but-not-really-vanilla/relations/dependencies

**Comment by Tfarcenim** [comment]
This is no longer possible as of 2.1
