### ISSUE TITLE
In construction mode. right clicking crashes game

### ISSUE THREAD

**Issue by itsdinkd** [Tfarcenim/DankStorageFabric#28]
When I have any dank out, and I right click somewhere in the world for placement, the game crashes.
1.17.1 
Fabric 
Latest dank storage version

--

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/26/21, 8:54 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "selectedItem" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25)
	at tfar.dankstorage.utils.Utils.getSelectedItem(Utils.java:144)
	at tfar.dankstorage.item.DankItem.useOnBlock(DankItem.java:308)
	at net.minecraft.item.ItemStack.useOnBlock(ItemStack:242)
	at net.minecraft.client.network.ClientPlayerInteractionManager.interactBlock(ClientPlayerInteractionManager:342)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient:1646)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1900)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1728)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1081)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tfar.dankstorage.utils.Utils.getSelectedItem(Utils.java:144)
	at tfar.dankstorage.item.DankItem.method_7884(DankItem.java:308)
	at net.minecraft.class_1799.method_7981(class_1799.java:242)
	at net.minecraft.class_636.method_2896(class_636.java:342)
	at net.minecraft.class_310.method_1583(class_310.java:1646)
	at net.minecraft.class_310.method_1508(class_310.java:1900)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cag000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['DaddyDanked'/1355, l='ClientLevel', x=1742.37, y=69.00, z=1303.01]]
	Chunk stats: 1024, 676
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,73,-176), Section: (at 0,9,0 in 12,4,-11; chunk contains blocks 192,0,-176 to 207,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 9582907 game time, 1518316 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, AntiqueAtlasExtra-v1.2.zip, Incendium - Optional Resource Pack.zip, charmonium/journeyman, Dramatic Skys Demo 1.3.zip, Default-Dark-Mode-1.17-(v1.3.0).zip, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 510679048 bytes (487 MiB) / 2046820352 bytes (1952 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e87
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 38219.94
	Virtual memory used (MB): 33316.54
	Swap memory total (MB): 5520.48
	Swap memory used (MB): 1226.27
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		ambientenvironment: Ambient Environment fabric-1.17.1-6.0.13
		amecsapi: Amecs API 1.1.5+mc21w16a
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.0
		aqupd: Caracal mob 1.17-1.2.2
		architectury: Architectury 2.2.21
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.5
		bclib: BCLib 0.2.4
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterbiomeblend: Better Biome Blend 1.17.0-1.2.3-fabric
		betterend: Better End 0.10.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		blockus: Blockus 2.2.7+1.17.1
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.0.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.0.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		cardinal-components-level: Cardinal Components API (world saves) 3.0.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.1
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chesttracker: Chest Tracker 1.0.11
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta38-1.17
		dankstorage: Dank Storage 2.1-1.17.1
		defaultsettings: DefaultSettings 3.0.3
		detailab: Detail Armor Bar 1.2.3+1.17.1
		dual_riders: DualRiders 1.0.5
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		expandedstorage: Expanded Storage 7.0.0-alpha.37
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricenchantments: Fabric Enchantments 0.3.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fasttransferlib: Fast Transfer Lib 0.5.5
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		gamemodeoverhaul: GamemodeOverhaul 1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.10
		gobber2: Gobber2 2.4.32
		hookshot: Hookshot 16.0
		horseinfo: Horse Info 0.3.0-1.17
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		illuminations: Illuminations 1.6.3
		inventoryprofilesnext: Inventory Profiles Next 0.8.4
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kibe: Kibe 1.8-BETA+1.17
		ksrch: Keybind Search 1.0.0
		kubejs: KubeJS 1605.3.10-build.9999
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.3.8
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.11
		ltr: LilTaterReloaded 1.1.14+1.17
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.5
		mcdw: MC Dungeons Weapons 3.3.4
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.1.1+0.4.2
		megane-kibe: megane-kibe 5.1.1+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.1+0.9.0
		megane-runtime: megane-runtime 5.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.1+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.1.1+1.1.1
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.9
		modmenu: Mod Menu 2.0.4
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		patchouli: Patchouli 1.17-54-FABRIC
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.5-beta+build.85
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		repurposed_structures: Repurposed Structures 2.1.6+1.17.1
		resourceful_tools: Resourceful Tools 1.1.18
		rhino: Rhino 1605.1.1-build.23
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		schmucks: Schmucks 1.4.0
		simple_backpack: SimpleBackpack 1.1.13
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.5-beta+build.85
		the_bumblezone: The Bumblezone - Fabric 3.0.7+1.17.1
		torcherino: Torcherino 15.0.0-alpha.3
		trinkets: Trinkets 3.0.2
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.0.2
		whereisit: Where Is It 1.13.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		witherite: Witherite 0.0.8-hotfix
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		xhp: xhp 1.0.9
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 3440x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/AntiqueAtlasExtra-v1.2.zip (incompatible), file/Incendium - Optional Resource Pack.zip (incompatible), charmonium/journeyman, file/Dramatic Skys Demo 1.3.zip, file/Default-Dark-Mode-1.17-(v1.3.0).zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Dank Storage (dankstorage)

**Comment by the-aterna-10** [comment]
I'm having the same issue on the same version

here's my crash log
[crash-2021-08-13_10.10.56-client.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6983013/crash-2021-08-13_10.10.56-client.txt)

**Comment by atrophy08** [comment]
Same! 
[crash-2021-08-13_19.40.40-client.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6985685/crash-2021-08-13_19.40.40-client.txt)

**Comment by atrophy08** [comment]
> Same!
> [crash-2021-08-13_19.40.40-client.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6985685/crash-2021-08-13_19.40.40-client.txt)

The first time this happened, I retained my inventory on the dank 1 but the second time was on dank 2 and I lost all my inventory.

**Comment by notarobot347** [comment]
I've had the same issue; however, it only happens for me upon loading a world and trying to use a dank in construction mode without first scrolling to a block within the dank. When I reload the world, the block that's in the first slot of the dank is placed correctly in the world. I think it's an issue with the dank's selector getting set to null upon world loading; when you scroll to a block after loading the world, it works just fine in the construction mode.

**Comment by Gerdathlete** [comment]
> I've had the same issue; however, it only happens for me upon loading a world and trying to use a dank in construction mode without first scrolling to a block within the dank. When I reload the world, the block that's in the first slot of the dank is placed correctly in the world. I think it's an issue with the dank's selector getting set to null upon world loading; when you scroll to a block after loading the world, it works just fine in the construction mode.

Exactly the issue that I ran into: https://pastebin.com/KdVUnrha

**Comment by itsdinkd** [comment]
doesn't look like the mod author is going to fix the crashes and bugs guys.
an alternative to this mod that wasn't bug tested at all (nice dank
storage) is upgradeable shulkers. it offers pick up and void.

**Comment by Tfarcenim** [comment]
> doesn't look like the mod author is going to fix the crashes and bugs guys.

Or maybe it's perhaps because I have a life outside of mods and can't afford to spend all of it catering to players that whine when anything isn't perfect.

> an alternative to this mod that wasn't bug tested at all (nice dank
storage) 

Now you're making up lies, just because a mod doesn't have 0 bugs on release 1.0 doesn't mean it wasn't bug tested, in fact, dank is one of my most heavily bug tested, (and patched) mods.

That being said, I don't have much spare time these days, so a fix might take months if it isn't PRed in.

**Comment by Gerdathlete** [comment]
> > doesn't look like the mod author is going to fix the crashes and bugs guys.
> 
> Or maybe it's perhaps because I have a life outside of mods and can't afford to spend all of it catering to players that whine when anything isn't perfect.
> 
> > an alternative to this mod that wasn't bug tested at all (nice dank
> > storage)
> 
> Now you're making up lies, just because a mod doesn't have 0 bugs on release 1.0 doesn't mean it wasn't bug tested, in fact, dank is one of my most heavily bug tested, (and patched) mods.
> 
> That being said, I don't have much spare time these days, so a fix might take months if it isn't PRed in.

This mod is the only reason the All of Fabric 4 pack crashes constantly. We're not whining, we just like your mod and want to continue using it, but game-breaking crashes make it a liability. Considering you don't have the time to support it, we'll just have to find other solutions.

Anyways, I'm just going to unsubscribe from this issue and move on. The AOF team will likely remove the mod, and hopefully find or make a mod with similar functionality, because it helps a great deal with reducing the amount of items on the floor in servers.

**Comment by itsdinkd** [comment]
Yes, what he said. we love your mod, and we're not complaining. I'm just letting people know that the chances of it being fixed right now are slim as its obvious you are busy. As for what I mentioned about not being bug tested,  there are just so many different crashes on the mod it made me seem that it wasn't, crashes that take seconds to reproduce. I apologize if I offended you.
