### ISSUE TITLE
[1.17.1] Crashing when Upgrading to Tier 5

### ISSUE THREAD

**Issue by kalinzange** [Tfarcenim/DankStorageFabric#30]
Hi,

So whenever I upgrade my dank to Tier 5, my client just crashes. Similar to #23 

[crash-2021-08-01_18.52.03-client.txt](https://github.com/Tfarcenim/DankStorageFabric/files/6913128/crash-2021-08-01_18.52.03-client.txt)

**Comment by kalinzange** [comment]
You can close this, Seems Item Scroller is sending the recipe through client-side which makes it crash

**Comment by Tfarcenim** [comment]
I've added a circumvent for the next release in case other mods decide to try crafting items clientside
