### ISSUE TITLE
Upgrading a Dank causes crash to desktop.

### ISSUE THREAD

**Issue by Zarepheth** [Tfarcenim/DankStorageFabric#39]
Was upgrading a Dank 2 (redstone) to Dank 3 (gold). When attempting to pull the upgraded Dank from the crafting grid, the game crashed to the desktop.

Crash Report: https://gist.github.com/Zarepheth/34728cf7e258bc39ef4b8cf6ebcff430#file-crash-report-2021-oct-14

**Comment by Zarepheth** [comment]
Upon returning to the world, I suffer another crash to desktop just as the client starts responding after connecting to the server (single player game).

2nd Crash Report: https://gist.github.com/Zarepheth/e8e43d27cca80e9972042641764e9592#file-crash-report-2-2021-oct-14

**Comment by Tfarcenim** [comment]
Weird

**Comment by Tfarcenim** [comment]
Ok, this one isn't possible anymore.
