### ISSUE TITLE
Dank losing contents when you change dimensions.

### ISSUE THREAD

**Issue by b4mmb4mm2** [Tfarcenim/DankStorageFabric#40]
When I updated to AOF4 1.00, the Dank I carry was all the suddenly empty. I wrote it off to updating. Went to the End and filled it back up. I put it down, picked it up, opened and closed it. Everything was still there. Went back to the overworld and everything was gone. 

I have 2 danks that are docked that I keep stuff in. They were fine. Swapped them around, everything stayed where it was. It appears to only affect mine when I carry it through dimensions.

**Comment by Tfarcenim** [comment]
This is no longer a thing
