### ISSUE TITLE
server corrupt 

### ISSUE THREAD

**Issue by MunchyG** [Tfarcenim/DankStorageFabric#42]
connected an item duct from chest to dank and now server crashes when the chunk loads  
[crash-2021-10-27_03.40.05-server.txt](https://github.com/Tfarcenim/DankStorageFabric/files/7421071/crash-2021-10-27_03.40.05-server.txt)

**Comment by GiviZU** [comment]
+1

**Comment by Tfarcenim** [comment]
fixed in 3.3
