### ISSUE TITLE
Upgrading Dank updates ID, losing inventory

### ISSUE THREAD

**Issue by lwskosa** [Tfarcenim/DankStorageFabric#48]
# To reproduce issue:

###Prerequisite:
* No Dock is used

1. Craft/give [Any] rank Dank
2. Take a note of ID
3. Add some items
4. Upgrade it to next rank using crafting grid (NOT Dock + upgrade card!)
5. ID gets updated along with Rank
6. Items you stored in Step 3 are now inaccessible

**Comment by lwskosa** [comment]
Is there any way to recover "lost" inventory due to this issue? (forcing ID, via config file or command)

**Comment by Tfarcenim** [comment]
Changing the nbt will change the inventory it points to which should work.

**Comment by lwskosa** [comment]
> Changing the nbt will change the inventory it points to which should work.

Thanks!
