### ISSUE TITLE
Multiple Stacks Destroyed using Dank Storage Sort

### ISSUE THREAD

**Issue by MonsterActual** [Tfarcenim/DankStorageFabric#5]
Multiple stacks of material in one Dank are destroyed when sorting with the Dank's 'Sort' button.
Dank was in Bag mode when I experienced this, did not test Chest mode.

![mystone](https://user-images.githubusercontent.com/64934524/91510238-78621680-e8aa-11ea-8311-52bbf7f7bd25.gif)

Dank vers. 1.1d
MC 1.16.1
All of Fabric 3 Modpack ver. 1.5.3

**Comment by Tfarcenim** [comment]
Hmm, this is still a problem in 1.6-1.16.2
