### ISSUE TITLE
Danks Upgrading an existing dank using a crafting table and placing items in the last row deletes them on the server's end

### ISSUE THREAD

**Issue by GoldenFurredFox** [Tfarcenim/DankStorageFabric#52]
I was playing AoF5 1.18.1 and when I made a dank 2 and put some items in the second row they got deleted. I had already used it as a dank 1 and it saved the contents but never considered the second row.

The mod version is 3.0.1 for 1.18.

Edit: As it turns out, it happens for any upgrade done in the crafting table after a dank is assigned an ID, but if it's upgraded while it has an ID of 0 then the new rows work fine until upgrading it again.

**Comment by Tfarcenim** [comment]
How was the dank upgraded, crafting table or upgrade card?

**Comment by GoldenFurredFox** [comment]
> How was the dank upgraded, crafting table or upgrade card?

Crafting table

**Comment by Tfarcenim** [comment]
I forgot that Minecraft treats an empty nbt value as 0, so I will have to ban it from being used as an id.  I will get a fix later tonight, hopefully it doesn't break too much.

**Comment by Tfarcenim** [comment]
Shouldn't be possible anymore
