### ISSUE TITLE
1.18.1 Dank 2.. Blocks are randomly vanishing

### ISSUE THREAD

**Issue by tacogerbil** [Tfarcenim/DankStorageFabric#53]
Found a geode and placed the blocks of Amethist into the Dank2.. they Vanished when placed into the 2nd row.  Oddly enough the 1st slot in the second row is locked.. it was locked when I first opened the Dank after creating it.  
Further testing showed that anything placed into that second row vanishes once you try to pick the item back up. 

![image](https://user-images.githubusercontent.com/12961907/146710587-62802287-4c05-436d-961a-448c1628a8ce.png)

[latest.log](https://github.com/Tfarcenim/DankStorageFabric/files/7742561/latest.log)

**Comment by Tfarcenim** [comment]
3.2 has a command to help with resetting inventory.
