### ISSUE TITLE
Off-hand messes with dank interactions

### ISSUE THREAD

**Issue by Adirelle** [Tfarcenim/DankStorageFabric#54]
Holding an item (say a torch) in off-hand makes interacting with dank and dock funny :
* when opening a dank in bag mode, the torch in off-hand is be used (e.g. placed in the world),
* one cannot sneak-right-click on a loaded dock to unload it: it does nothing; having both hand empty is required.

These are lesser bugs but they are annoying nonetheless.

**Comment by Tfarcenim** [comment]
First one is fixable, second one isn't

**Comment by Tfarcenim** [comment]
The second one is a vanilla issue, as it can be triggered by holding torches in the offhand while looking at a chest.
