### ISSUE TITLE
FABRIC version not listed in CurseForge Desktop

### ISSUE THREAD

**Issue by silentnyte** [Tfarcenim/DankStorageFabric#61]
The FABRIC version is not correctly tagged to add to a profile in the CurseForge desktop mod manager. Currently both the FORGE and FABRIC version show up under FORGE profiles.

**Comment by Tfarcenim** [comment]
Not seeing the issue, almost all of them have the tag now and the one's that don't you shouldn't be using anyways.

**Comment by silentnyte** [comment]
> Not seeing the issue, almost all of them have the tag now and the one's that don't you shouldn't be using anyways.

Here is Fabric 1.16.5
https://i.imgur.com/gc2SFjk.png

Here is Forge 1.16.5
https://i.imgur.com/sDcp1Q4.png
