### ISSUE TITLE
Error "Dank Item Level 6 cannot open Dank Inventory Level 5"

### ISSUE THREAD

**Issue by NemmieDragon** [Tfarcenim/DankStorageFabric#62]
I am having a problem with upgrading my storage. When I go from 5 to 6 and then try to open it I get the error "Dank Item Level 6 cannot open Dank Inventory Level 5" this one is done on a crafting station slab from Improved Stations.

 

Dank Storage v 1.18.1-3.44

Improved Stations v 2.0.8

Modpace All of Fabric 5 v 0.2.9

 

Minecraft 1.18.1

Fabric Loader 0.12.12

Java 17.0.1 64bit

**Comment by Tfarcenim** [comment]
Update to 1.18.1-3.4.1
