### ISSUE TITLE
Dank Storage upgrade issues

### ISSUE THREAD

**Issue by pezda13** [Tfarcenim/DankStorageFabric#63]
I am having an issue with this mod. I am currently playing on a server with a friend and his Dank works fine. Mine is having an assortment of issues. The first one had a locked space that could not be interacted with and anything placed in the third row or beyond would disappear, it could hold thousands of objects in each spot. The next two I created only functioned as a tier one Dank regardless of the actual  level. Any ideas on what is happening, or how to fix? Thanks
Dank Storage 3.1-1.18.1
All of Fabric 5 -0.2.5

**Comment by Tfarcenim** [comment]
Your Dank Storage version is far out of date.
