### ISSUE TITLE
Issue with upgrading Danks from one lvl to the next with items inside

### ISSUE THREAD

**Issue by Meepin** [Tfarcenim/DankStorageFabric#65]
I just got an unfortunate bug while playing a SP world with the Dank Storage Mod, I received the Msg "Dank Item Level 4 cannot open dank Inventory Level 3". I can only assume this because I upgraded the dank while it contained items and the NBT that stores the data is not linking properly. Is this a known bug, or is there a way to correct it without spawning/crafting a new one and loosing the items inside?
![image](https://user-images.githubusercontent.com/5864626/149903928-de2b1f04-b952-49f0-a48e-bd3d979d365f.png)

**Comment by Tfarcenim** [comment]
This was fixed in 3.4.1 already, update
