### ISSUE TITLE
Dank interface frequency type box always highlighted

### ISSUE THREAD

**Issue by callmejay758** [Tfarcenim/DankStorageFabric#66]
I'm not sure if this is intentional or there's something i'm missing but the textbox for typing in a new frequency and/or saving it seems broken. Its always accepting input when the dank interface is opened. Very annoying when trying to use hotkeys that sort my inventory for e.g.

**Comment by Tfarcenim** [comment]
Fixed in 3.5, but that's a breaking change so I would be careful.
