### ISSUE TITLE
All the danks lost their inventories

### ISSUE THREAD

**Issue by 4nner** [Tfarcenim/DankStorageFabric#67]
Using version 3.4.1
Can't really understand how it happened, but since I started the server every dank lost its inventory.
Tried loading a backup in which the danks had their content saved, but no success at all.
Any ideas on how to solve this / retrieve the content of the danks?
I am unable to locate the file in which the mod saves the content

**Comment by Tfarcenim** [comment]
It's saved in worldsaveddata, do you have a copy of your world file that I can look at?

Without further information, I can't say whether it's the fault of Dank Storage or not.

**Comment by 4nner** [comment]
I've uploaded a copy of a backup in which Danks still had their inventories. However, when I load this backup the inventories are gone. Let me know if I can provide you any more info that might help find the issue.
https://www.swisstransfer.com/d/c81342b3-9c82-4cb9-9731-3c6d864a6e91

**Comment by 4nner** [comment]
Update: apparently some danks of different players have now the same ID, could this happen because dank IDs got mixed ?

**Comment by Tfarcenim** [comment]
No, it happens if the NBT of the danks get messed with.

**Comment by 4nner** [comment]
Any ideas of how all of this could have happened?

**Comment by Tfarcenim** [comment]
No idea, but I made inventories save in the external data folder so they're easier to find, unfortunately this means it's a breaking change as all inventories on existing worlds will be wiped.
