### ISSUE TITLE
Danks can pickup the hook projectile from Hookshot, causing some issues.

### ISSUE THREAD

**Issue by WhitePhant0m** [Tfarcenim/DankStorageFabric#69]
https://github.com/CammiePone/Hookshot/issues/24

When a Dank is set on any pickup mode it can pickup the hook projectile from a hookshot, and cause player to float until another hook is fired.

Thought I should report it here since Hookshot dev said that the issue has do with the way Danks pickup things.

Not sure how easy a fix would be, but would be nice if it could get fixed.

**Comment by Tfarcenim** [comment]
Fixed, dank no longer tries to pick up empty items.
