### ISSUE TITLE
Powder Snow

### ISSUE THREAD

**Issue by Noxally** [Tfarcenim/DankStorageFabric#70]
Using a powder snow thats stored in your dank nul replaces your  dank will an empty bucket. How do you change the ID of a dank?

**Comment by Tfarcenim** [comment]
> How do you change the ID of a dank?

Click on the right side and type the new id.

> Using a powder snow thats stored in your dank nul replaces your dank will an empty bucket.

This is a vanilla blunder that is patchable but out of scope for this mod so I will be adding it to the blacklist.
