### ISSUE TITLE
In-game ID locking/unlocking & editing (feature request)

### ISSUE THREAD

**Issue by Suitov** [Tfarcenim/DankStorageFabric#71]
Could you please add an in-game way to change the ID of a dank, and/or **lock** the ID? Preferred behaviour would be for ID to be initially locked as soon as it's generated, but permit the user to unlock it and change it.

Without a simple way to fix danks with wrong IDs, this mod seems unusable, which is a shame because I'd really like to play with it more, but I'm afraid "edit the NBT" is too much to ask (especially with cheats being disabled on the server I was using to test it).

Description of problem encountered: I began trying out the mod with what I expected to be a very simple first application: setting up some static docked danks in my storage room. I made a few danks and put some coal and emeralds into two of them. I also renamed the coal one on an anvil, and so far the coal one has behaved as I expected. However, the emerald one immediately went bananas: I put stuff in it and then experimented with putting the emerald dank into a dock, but when I interacted while docked, its ID had incremented and the items had become inaccessible. I found no way to decrease the ID, but it did increase several more times after I broke the dock, re-docked it, and tried upgrading it to red to see if any of that fixed it (it didn't). It didn't seem to increment by 1 or anything else predictable; at some point it jumped from something like 3 to 13. It's now apparently stopped changing IDs every time (don't even know what I did to cause that), and remains stuck at 15 while its items are in ID 2 or so.

I don't mind if the answer is creating a new dank, but there seems to be no way to assign IDs manually to new danks, so that hasn't worked yet either.

A few emeralds don't matter in the grand scheme of things, but I would want to use these blocks in machines and such, which would require them to be completely trustworthy and maintain their IDs no matter what. Hence this request.

I do realise this would become more complex when you factor in multiplayer worlds, and might require an ID table with reserved numbers or something, but while the mod's still in development(?), just a simple edit feature would be really sanity-saving.

**Comment by Tfarcenim** [comment]
> Could you please add an in-game way to change the ID of a dank, and/or lock the ID? Preferred behaviour would be for ID to be initially locked as soon as it's generated, but permit the user to unlock it and change it.

This feature has been present since 3.4 or so.  In addition, there's a few (OP-only) commands to help with unbricking them.

> Description of problem encountered: I began trying out the mod with what I expected to be a very simple first application: setting up some static docked danks in my storage room. I made a few danks and put some coal and emeralds into two of them. I also renamed the coal one on an anvil, and so far the coal one has behaved as I expected. However, the emerald one immediately went bananas: I put stuff in it and then experimented with putting the emerald dank into a dock, but when I interacted while docked, its ID had incremented and the items had become inaccessible. I found no way to decrease the ID, but it did increase several more times after I broke the dock, re-docked it, and tried upgrading it to red to see if any of that fixed it (it didn't). It didn't seem to increment by 1 or anything else predictable; at some point it jumped from something like 3 to 13. It's now apparently stopped changing IDs every time (don't even know what I did to cause that), and remains stuck at 15 while its items are in ID 2 or so.

How are you getting it to increment from docking and redocking?  As far as I know, all forms of that have been killed in 3.3 and 3.4.  More importantly is this on a FRESH world with the mod.

**Comment by Suitov** [comment]
> This feature has been present since 3.4 or so. In addition, there's a few (OP-only) commands to help with unbricking them.

Ah, then I bet it's because I'm on 1.17.1 (stuck there because my storage mod hasn't updated, ironically). I didn't notice that that was such an old version of the mod compared to current version. My apologies!
