### ISSUE TITLE
Finding NBT data of older instances of Danks

### ISSUE THREAD

**Issue by redace001** [Tfarcenim/DankStorageFabric#72]
... I made inventories save in the external data folder so they're easier to find, unfortunately this means it's a breaking change as all inventories on existing worlds will be wiped.

_Originally posted by @Tfarcenim in https://github.com/T5farcenim/DankStorageFabric/issues/67#issuecomment-1023772991_

For olderversions, can you tell us specifically which file(s) store the original dank inventory is located?  Even if it's just to get a list of items that can be 'given' back to the dank owner.  Been looking for it in the world folder files with NBTExplorer, but so far can only see the dank references in player inventory.

Nice that you have moved it to an easier to see .dat file now , but a way to update from older to newer would be appreciated, even if it's manual.

**Comment by Tfarcenim** [comment]
> For olderversions, can you tell us specifically which file(s) store the original dank inventory is located?

I have no idea, maybe it's deep inside the level.dat folder or something, that was the whole reason for moving it in the first place.
