### ISSUE TITLE
Locked Slots not working correctly

### ISSUE THREAD

**Issue by mysteryAftermath** [Tfarcenim/DankStorageFabric#74]
Minecraft: 1.18.2
Fabric Loader: 0.14.6
Fabric API: 0.53.4
Dank Storage: 1.18.2-3.7

Locked Slots behave incorrectly when taking items out of dank.
1: Taking items out of a slot which has exactly the max stack size of an item will leave one item in the slot - Correct Behavior
2: Taking items out of a locked slot which has less then the max stack size of the item will take all of the items out of that slot - Bug
3: Hoppers, Hopper Minecarts, etc. do not respect locked slots at all - Not sure if this is intended or not

**Comment by ouroborus** [comment]
4. Sort does not respect locked slots

**Comment by knzai** [comment]
I'm seeing 2. as well (in the All of Fabric 5 modpack)

**Comment by PINPAL** [comment]
Experiencing both issues in `dankstorage-1.18.2-3.7.2`

Locked slots are not respected in automation now when shift clicking/left clicking slots. The only time they work correctly is droping items out of the dank with Crouch + Drop.

**Comment by PINPAL** [comment]
Can the changes from the Forge version be merged into Fabric? 
https://github.com/Tfarcenim/Dank-Storage/issues/108

**Comment by Tfarcenim** [comment]
Yeah, the old slot implementation was very broken so it got a rewrite, will take some time to merge the changes into fabric as they use slightly different inventory apis.

**Comment by Tfarcenim** [comment]
Brought over the changes from Forge which is
Items are no longer left behind, instead there is a ghost which blocks item insertions.
Respects shiftclicking, dragging and hoppers and other automation
Attempting to compress or sort the contents will unlock every slot, may change in the future
