### ISSUE TITLE
Compresses reversible 3x3 recipes deletes inventory

### ISSUE THREAD

**Issue by TiphaineLAURENT** [Tfarcenim/DankStorageFabric#76]
I think the title is self explanatory but I will add some context :

I add a tier 1 dank storage filled with 300 coals (1x 256stack + 4), some redstone and some amethysts in it.
After clicking the Compresses... button, only blocks of coal and coals remains.

I tried switich the frequency but any other value than 0 give an error so it is not a kind of duplication.

PS : I don't have any logs and screenshot are not really useful in that case. The game did not crash or anything.

**Comment by Tfarcenim** [comment]
Was able to reproduce with a simpler example, 257 coal + 1 stack of amethyst is enough to trigger it.
