### ISSUE TITLE
Losing items in the dank placed in a dock when exiting the singleplayer mode

### ISSUE THREAD

**Issue by NoneMore** [Tfarcenim/DankStorageFabric#77]
Minecraft Verision 1.16.5 Fabric 0.13.3/0.14.8(Both tested) for mod version 1.10a
No other mods

**Comment by NoneMore** [comment]
Solved by changing mod version to 1.10,and items are gone after updating the mod version to 1.10a
So there must be some problems with 1.10a

**Comment by Tfarcenim** [comment]
Yeah, versions older than 1.18 on the Fabric side are scuffed, nothing I can do about it though as my time is limited and I need to prep for 1.18 - 1.20.
