### ISSUE TITLE
No "Chest Mode" available in the "All of Fabric" modpack

### ISSUE THREAD

**Issue by ThorToddson** [Tfarcenim/DankStorageFabric#8]
-Copied from Dank Storage Repository/Issues - Sorry about the duplication...

All features of Dank-Storage seem to work except DSUs will not go into Chest Mode. Bound key will transition from Construction to Bag modes only.

Great Mod - even without Chest Mode!

**Comment by MissPotato** [comment]
This is intended, use the Dank Dock
