### ISSUE TITLE
What is Red Print for?

### ISSUE THREAD

**Issue by QiYiJun** [Tfarcenim/DankStorageFabric#80]
I want to know how Red Print is used, or what is it used for?
I'm shift-right on the dock, I just see the name change.

**Comment by Tfarcenim** [comment]
It's for copying frequencies and setting between danks/docks.

**Comment by Garonne** [comment]
Does it work? How does it work? Is it different on forge (since I'm playing on forge, but didn't want to open a new issue as this one actually fits my question.

**Comment by troyheady2** [comment]
i have the same questions.  I don't see any documentation..   I have used the red print accidentally. but I am unsure how to copy frequency and apply that frequency   from/to a dank in my hand or one in a dock.

any guidance would be greatly appreciated

**Comment by QiYiJun** [comment]
> i have the same questions. I don't see any documentation.. I have used the red print accidentally. but I am unsure how to copy frequency and apply that frequency from/to a dank in my hand or one in a dock.
> 
> any guidance would be greatly appreciated

Crouch down with redprint and right click on the dock to get the frequency. An empty dock has a frequency of -1, and if you put dank in the dock, you get the frequency of dank. Pick up redprint in your backpack(inventory) and right-click on dank to use the frequency on redprint. The same frequency of dank is like an ender chest.

**Comment by troyheady2** [comment]
thank you for the information that makes it much clearer.

I thought I accidentally got the red print to work with a dank in my inventory / hands  ...  not in dock. 
I had  red print set to frequency (copied [shift-right click] ]from another dank in dock) and placed it in my off hand
and opened a new (no freq, -1) dank for the first time.

of course, I can't get it to repeat now  :)

thank you again for the info.

If you can Please post the  Red Print instructions  to your readme / curseforge.... 
others will probably have similar questions....  and it would cut down on issue tickets ;)

and Thank you for taking the time to write and support this mod

People only complain in these issues...... I say you did a good thing!
and Thank you

**Comment by QiYiJun** [comment]
> 
I am not sure whether redprint will continue to exist, because I did not see the recipes file in the latest version of 1.19.2.  Maybe it was deleted by accident? That's up to author Tfarcenim
