### ISSUE TITLE
Filtered Pickup does not respect locked slots with 0 in them.

### ISSUE THREAD

**Issue by PINPAL** [Tfarcenim/DankStorageFabric#84]
# Info
Mod Version: `dankstorage-1.18.2-3.8.1`
Game Version: `1.18.2`

I haven't tested 1.19 but I assume the same issue applies.

# Behaviour
When "Filtered Pickup" mode is enabled it only picks up items that have a quanity of greater than or equal to 1.

# Expected Behaviour
When "Filtered Pickup" mode is enabled, all items that are in the dank (including ones that have been locked but have 0 items) should automatically go into the dank.

# Steps to Reproduce
1. Obtain a dank
2. Put an item into the dank
3. Lock the slot with the item in it
4. Remove the item from the dank causing it to enter a "ghost" state
5. Enable "Filtered Pickup" mode
6. Drop the item on the floor 
7. Pickup the item off the floor
8. Observe item enters player inventory NOT the dank.#83 

# Workaround for Issue
For those experiencing the issue, you can enable "Pickup All" mode on your dank and ensure that all slots of it are filled, this will allow it to pickup items but only ones you have filtered will go in.

**Comment by Tfarcenim** [comment]
Fun, looks like item pickup is getting a rewrite for better or for worse.
