### ISSUE TITLE
[Parity Request] Display item name as tooltip

### ISSUE THREAD

**Issue by MissPotato** [Tfarcenim/DankStorageFabric#88]
Terribly sorry, I now understand why I thought I was so many versions behind, and not that the feature you were adding was coming in an upcoming update. I'm using Fabric Dank-Storage and accidentally posted it on your forge version 
https://github.com/Tfarcenim/Dank-Storage/issues/196. I was checking to see if it wasn't already requested in the forge version and must have clicked the wrong button.

Thank you for your time!

**Comment by Tfarcenim** [comment]
It will be added in 1.19.4, I'm not creating a new release for a minor feature
