### ISSUE TITLE
Nuggets of XP from Create dupe

### ISSUE THREAD

**Issue by MissPotato** [Tfarcenim/DankStorageFabric#89]
Create has an item called the "Nugget of XP" when the player sneaks and uses the item the entire stack is consumed dropping 3 experience each at the players feet. If you put these nuggets inside a Dank Null, put it into construction mode, and then consume the nuggets an XP orb equal to the total large stack size. However, the actual nuggets aren't reduced and can be consumed infinitely. 

Create: 0.5.0.i-961
DankStorage: 4.3
Fabric: 0.14.17
Fabric API: 0.75.1

**Comment by Tfarcenim** [comment]
https://github.com/Fabricators-of-Create/Create/blob/mc1.19/fabric/dev/src/main/java/com/simibubi/create/content/curiosities/ExperienceNuggetItem.java#L30 the way they're handling item usage is inconsistent with vanilla which causes dupes

This will need to be fixed on their end, for now add the item to `dankstorage:blacklisted_usage` tag

**Comment by MissPotato** [comment]
Ah, sorry, I'll report it to them, thank you!
